FROM php:8.2-apache

RUN apt-get update && apt-get install -y --no-install-recommends \
  libzip-dev \
  libpng-dev \
  libjpeg-dev \
  libfreetype6-dev \
  zip \
  bzip2 \
  unzip \
  apt-utils \
  curl \
  nano \
  libpq-dev \
  zlib1g-dev \
  && docker-php-ext-configure gd --with-freetype --with-jpeg \
  && docker-php-ext-install pdo_pgsql zip gd \
  && apt-get clean && rm -rf /var/lib/apt/lists/*


# Instalando o Composer
RUN php -r "copy('http://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"


# Configura permissões para o diretório de trabalho
RUN chown -R www-data:www-data /var/www/html \
  && chmod -R 755 /var/www/html

COPY apache/custom_apache.conf /usr/local/apache2/conf/custom_apache.conf

RUN echo "Include /usr/local/apache2/conf/custom_apache.conf" >> /usr/local/apache2/conf/httpd.conf

EXPOSE 80
EXPOSE 443
EXPOSE 8000
EXPOSE 5432


WORKDIR /var/www


CMD ["apache2-foreground"]