FROM php:8.2-apache

RUN apt-get update && apt-get install -y --no-install-recommends \
  zip \
  bzip2 \
  unzip \
  apt-utils \
  curl \
  nano \
  libpq-dev \
  libzip-dev \
  postgresql-client \
  && docker-php-ext-install pdo_pgsql pgsql zip \
  && apt-get clean && rm -rf /var/lib/apt/lists/*


# Instalando o Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


# Instalando o Node.js
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - \
  && apt-get install -y nodejs

# Configura permissões para o diretório de trabalho
RUN chown -R www-data:www-data /var/www/html \
  && chmod -R 755 /var/www/html

COPY apache/custom_apache.conf /usr/local/apache2/conf/custom_apache.conf

RUN echo "Include /usr/local/apache2/conf/custom_apache.conf" >> /usr/local/apache2/conf/httpd.conf

EXPOSE 80 443

WORKDIR /var/www


CMD ["apache2-foreground"]